#######################################################
# 
# IACEVSEController.py
# Python implementation of the Interface IACEVSEController
# Generated by Enterprise Architect
# Created on:      07-Jan-2021 11:50:56
# Original author: Fabian.Stichtenoth
# 
#######################################################
from shared.v2gMessages.msgDef.ACEVSEStatusType import ACEVSEStatusType
from secc.evseController.IEVSEController import IEVSEController


class IACEVSEController(IEVSEController):
    def get_ac_evse_charge_parameter(self):
        """Returns the charge parameter for AC charging
        :return: The EVSE specific charge parameter for the current charging session
        """
        pass

    @staticmethod
    def get_ac_evse_status(evseNotification):
        """Returns the EVSE status for AC charging comprising notification, maxDelay and RCD
        :return: The EVSE specific status
        """
        pass
