#######################################################
# 
# StartSECC.py
# Python implementation of the Class StartSECC
# Generated by Enterprise Architect
# Created on:      07-Jan-2021 11:52:15
# Original author: Fabian.Stichtenoth
# 
#######################################################
import logging
import threading

from secc.session.V2GCommunicationSessionHandlerSECC import V2GCommunicationSessionHandlerSECC
from secc.transportLayer.TCPServer import TCPServer
from secc.transportLayer.TLSServer import TLSServer
from secc.transportLayer.UDPServer import UDPServer
from shared.enumerations.GlobalValues import GlobalValues
from shared.utils.MiscUtils import MiscUtils


class StartSECC:

    def __init__(self, args):
        """
        Main method that initiates properties object, initializes server, starts threads and initializes the
        V2GCommunicationSessionHandlerEVCC.
        :param args:
        :return None:
        """

        MiscUtils.set_v2g_entity_config(str(GlobalValues.SECC_CONFIG_PROPERTIES_PATH))

        udp_server = UDPServer.get_instance()
        tcp_server = TCPServer.get_instance()
        tls_server = TLSServer.get_instance()

        if not udp_server.initialize() or not tcp_server.initialize() or not tls_server.initialize():
            logging.critical("Unable to start SECC because UDP, TCP or TLS server could not be initialized")
        else:
            udp_server_thread = threading.Thread(target=udp_server, name="UDPServerThread")
            tcp_server_thread = threading.Thread(target=tcp_server, name="TCPServerThread")
            tls_server_thread = threading.Thread(target=tls_server, name="TLSServerThread")

            V2GCommunicationSessionHandlerSECC()

            udp_server_thread.start()
            tcp_server_thread.start()
            tls_server_thread.start()
