#######################################################
# 
# StartEVCC.py
# Python implementation of the Class StartEVCC
# Generated by Enterprise Architect
# Created on:      07-Jan-2021 11:05:40
# Original author: Fabian.Stichtenoth
# 
#######################################################
from evcc.session.V2GCommunicationSessionHandlerEVCC import V2GCommunicationSessionHandlerEVCC
from shared.utils.MiscUtils import MiscUtils
from shared.enumerations.GlobalValues import GlobalValues


class StartEVCC:

    @staticmethod
    def __init__(*args: str) -> None:
        """
        Main method that initiates properties object and initializes the V2GCommunicationSessionHandlerEVCC.
        :param args:
        :return None:
        """
        MiscUtils.set_v2g_entity_config(str(GlobalValues.EVCC_CONFIG_PROPERTIES_PATH))
        V2GCommunicationSessionHandlerEVCC()
