#######################################################
# 
# WaitForSessionStopRes.py
# Python implementation of the Class WaitForSessionStopRes
# Generated by Enterprise Architect
# Created on:      07-Jan-2021 11:18:14
# Original author: Fabian.Stichtenoth
# 
#######################################################
from shared.messageHandling.ReactionToIncomingMessage import ReactionToIncomingMessage
from shared.messageHandling.TerminateSession import TerminateSession
from shared.v2gMessages.msgDef.SessionSetupResType import SessionSetupResType
from evcc.session.V2GCommunicationSessionEVCC import V2GCommunicationSessionEVCC
from evcc.states.ClientState import ClientState


class WaitForSessionStopRes(ClientState):

    def __init__(self, comm_session_context: V2GCommunicationSessionEVCC):
        super().__init__(comm_session_context)

    def process_incoming_message(self, message) -> ReactionToIncomingMessage:
        """
        Initiates check if message is valid. If so, session is terminated as planned, if nit, session is terminated with
        an error message
        :param message:
        :return: ReactionToIncomingMessage
        """
        if self.is_incoming_message_valid(message, SessionSetupResType.__class__):
            return TerminateSession("V2G communication session will be stopped successfully", True)

        else:
            return TerminateSession("Incoming message raised an error")
