#######################################################
# 
# IACEVController.py
# Python implementation of the Interface IACEVController
# Generated by Enterprise Architect
# Created on:      07-Jan-2021 11:00:38
# Original author: Fabian.Stichtenoth
# 
#######################################################
from shared.v2gMessages.msgDef.PhysicalValueType import PhysicalValueType
from evcc.evController.IEVController import IEVController


class IACEVController(IEVController):

    def adjust_max_current(self, evse_max_current: PhysicalValueType) -> None:
        """Indicates the maximum line current per phase the EV can draw (as allowed by the
        SECC)
        :param evse_max_current:
        :return None:
        """
        pass

    def get_ac_ev_charge_parameter(self):
        """Returns the charge parameter for AC charging
         :return JAXBElement<ACEVChargeParameterType>: The battery specific charge parameter for the current charging
        session
        """
        pass
