#######################################################
# 
# IBackendInterface.py
# Python implementation of the Interface IBackendInterface
# Generated by Enterprise Architect
# Created on:      07-Jan-2021 11:47:43
# Original author: Fabian.Stichtenoth
# 
#######################################################
from shared.v2gMessages.msgDef.CertificateChainType import CertificateChainType
from shared.v2gMessages.msgDef.SAScheduleListType import SAScheduleListType
from secc.session.V2GCommunicationSessionSECC import V2GCommunicationSessionSECC


class IBackendInterface:

    def get_contract_certificate_chain(self, arg) -> CertificateChainType:
        """Provides a certificate chain coming from a secondary actor with the leaf
        certificate being the contract certificate and possible intermediate
        certificates (Sub-CAs) included.  This interface is to be used for the
        CertificateUpdate
        :param arg:
        :return: CertificateChainType
        """
        pass

    def get_contract_certificate_private_key(self):
        """Provides the private key belonging to the contract certificate.
        :return: PrivateKey of the contract certificate
        """
        pass

    def get_cps_certificate_chain(self) -> CertificateChainType:
        """Provides a certificate chain coming from a secondary actor with the leaf
        certificate being the provisioning certificate and possible intermediate
        certificates (sub CAs) included.
        :return: Certificate chain for provisioning certificate
        """
        pass

    def get_cps_leaf_private_key(self):
        """Provides the private key belonging to the SA provisioning certificate.
        :return: PrivateKey of the SA provisioning certificate
        """
        pass

    def get_mo_sub_ca2private_key(self):
        """Provides the private key belonging to the MO Sub-CA 2 certificate (signature of
        SalesTariff).
        :return: PrivateKey of the MO Sub-CA 2 certificate
        """
        pass

    def get_sa_schedule_list(self, max_entries_sa_schedule_tuple: int, departure_time, xml_signature_ref_elements,
                             selected_sa_schedule_tuple_id=None) -> SAScheduleListType:
        """Provides a list of schedules coming from a secondary actor (SAScheduleList)
        with pMax values and optional tariff incentives which shall influence the
        charging behaviour of the EV.
        :param max_entries_sa_schedule_tuple: int
        :param departure_time:
        :param xml_signature_ref_elements:
        :param selected_sa_schedule_tuple_id:
        :return: An SASchedulesType element with a list of secondary actor schedules
        """
        pass

    def set_comm_session_context(self, comm_session_context: V2GCommunicationSessionSECC):
        """Provides a reference to the current communication session for this backend
        interface.
        :param comm_session_context: V2GCommunicationSessionSECC
        :return: None
        """
        pass
