#######################################################
# 
# StatefulTransportLayerServer.py
# Python implementation of the Class StatefulTransportLayerServer
# Generated by Enterprise Architect
# Created on:      07-Jan-2021 12:06:25
# Original author: Fabian.Stichtenoth
# 
#######################################################
import logging

from shared.utils.MiscUtils import MiscUtils


class StatefulTransportLayerServer:

    def __init__(self):
        self._server_address = None
        self._server_port = 0

    def get_server_address(self):
        """
        Returns the _server_address
        :return _server_address:
        """
        return self._server_address

    def get_server_port(self):
        """
        Returns the _server_port
        :return _server_port:
        """
        return self._server_port

    def initialize(self):
        """
        Sets server port and address and returns True after completion
        :return: bool
        """
        self.set_server_port(MiscUtils.get_random_port_number())
        self.set_server_address(MiscUtils.get_link_local_address())

        return True

    def set_server_address(self, server_address):
        """
        Sets the _server_address
        :param server_address:
        :return: None
        """
        self._server_address = server_address
        pass

    def set_server_port(self, server_port):
        """
        Sets the _server_port
        :param server_port:
        :return: None
        """
        self._server_port = server_port
        pass

    def stop(self):
        pass
